### ISSUE TITLE
Bug: unsupported format found in riff chunk: WAVE-

### ISSUE THREAD

**Issue by BigGitWorld** [SKKbySSK/coast_audio#22]
Hello.
I'm using this package in ubuntu 22.04.
When I pass a wav file to the ``AudioFileDataSource``:
```
final dataSource = AudioFileDataSource(file: File('my-wav-file.wav'), mode: FileMode.read);
final WavAudioDecoder decoder = WavAudioDecoder(dataSource: dataSource);
```
the below error is shown:
```
unsupported format found in riff chunk: WAVE-
```
It seems that this package can not correctly decode header of wav file.
What is problem?

**Comment by SKKbySSK** [comment]
Hi @BigGitWorld. Thanks for the bug report.

Can you provide the (header of) wav file?
I think 44 bytes of data should be enough to analyze the header.

**Comment by AndroidDesigner** [comment]
> Hi @BigGitWorld. Thanks for the bug report.
> 
> Can you provide the (header of) wav file? I think 44 bytes of data should be enough to analyze the header.

Hello dear @SKKbySSK 
Its my [wav](https://github.com/SKKbySSK/coast_audio/files/14461420/file.zip) file.

**Comment by SKKbySSK** [comment]
Hi @AndroidDesigner . Thanks for providing the file.
I got a `FormatException` instead of the commented error.

But it looks like the text encoding problem and I've fixed it on this PR: https://github.com/SKKbySSK/coast_audio/pull/23
You can test it by writing this dependency
```yaml
  coast_audio:
    git:
      url: https://github.com/SKKbySSK/coast_audio.git
      ref: feature/fix-wav-decoder
      path: packages/coast_audio
```
